version: "3.8"
services:
  # auth-1:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - app-network

  # auth-2:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - app-network

  # user-1:
  #   build:
  #     context: ./user
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001"
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - app-network

  # user-2:
  #   build:
  #     context: ./user
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001"
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - app-network

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - auth-1
  #     - auth-2
  #     - user-1
  #     - user-2
  #   networks:
  #     - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
